root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main.exe ."
  bin = "tmp/main.exe"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  stop_on_error = true
  send_interrupt = false

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[screen]
  clear_on_rebuild = true